### ISSUE TITLE
Categories are missing from appstream data

### ISSUE THREAD

**Issue by bbhtt** [flathub/cool.ldr.lfy#1]
https://github.com/yuhldr/lfy/blob/ec212e974478987cc39845b50623a3fbc448dd2d/src/data/cool.ldr.lfy.in.in.desktop#L7

This is due to the desktop file having a low quality category that is filtered by appstream
Please define a proper category from https://specifications.freedesktop.org/menu-spec/latest/apa.html

**Comment by yuhldr** [comment]
v0.0.6: Utility
thanks
